source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'AppTapia' do
# Comment this line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

#    pods
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'GoogleWebRTC'
pod 'CryptoSwift', '0.7.2'
pod 'Socket.IO-Client-Swift'
# pod 'SocketRocket'
pod 'MBProgressHUD'
pod 'DDPatternLock'
pod 'PhoneNumberKit'
pod 'RealmSwift'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
# pod 'SlidingTabBar'
pod 'ReachabilitySwift'
pod 'BiometricAuthentication'
pod 'Eureka'
pod 'ImageRow', '~> 3.0'
end

post_install do |installer|
installer.pods_project.targets.each do |target|
target.build_configurations.each do |config|
config.build_settings['SWIFT_VERSION'] = '3.0'
end
end
end
